USE [master]
GO
/****** Object:  Database [FieldForceDb]    Script Date: 9/21/2019 10:13:27 PM ******/
CREATE DATABASE [FieldForceDb]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'FieldForceDb', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FieldForceDb.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'FieldForceDb_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\FieldForceDb_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [FieldForceDb].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [FieldForceDb] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [FieldForceDb] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [FieldForceDb] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [FieldForceDb] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [FieldForceDb] SET ARITHABORT OFF 
GO
ALTER DATABASE [FieldForceDb] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [FieldForceDb] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [FieldForceDb] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [FieldForceDb] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [FieldForceDb] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [FieldForceDb] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [FieldForceDb] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [FieldForceDb] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [FieldForceDb] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [FieldForceDb] SET  DISABLE_BROKER 
GO
ALTER DATABASE [FieldForceDb] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [FieldForceDb] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [FieldForceDb] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [FieldForceDb] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [FieldForceDb] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [FieldForceDb] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [FieldForceDb] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [FieldForceDb] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [FieldForceDb] SET  MULTI_USER 
GO
ALTER DATABASE [FieldForceDb] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [FieldForceDb] SET DB_CHAINING OFF 
GO
ALTER DATABASE [FieldForceDb] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [FieldForceDb] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
USE [FieldForceDb]
GO
/****** Object:  Table [dbo].[Team]    Script Date: 9/21/2019 10:13:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Team](
	[id] [int] IDENTITY(1,1) NOT NULL,
	[teamName] [varchar](50) NOT NULL,
 CONSTRAINT [PK_Team] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserMembership]    Script Date: 9/21/2019 10:13:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserMembership](
	[userId] [int] NOT NULL,
	[password] [varchar](50) NOT NULL,
 CONSTRAINT [PK_UserMembership] PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserProfile]    Script Date: 9/21/2019 10:13:28 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserProfile](
	[userId] [int] IDENTITY(1,1) NOT NULL,
	[userName] [varchar](50) NOT NULL,
	[title] [varchar](100) NOT NULL,
 CONSTRAINT [PK_UserProfile] PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [FieldForceDb] SET  READ_WRITE 
GO
